-- CREATE TABLE lottery_raw (
--     id SERIAL PRIMARY KEY,
--     draw_data JSONB,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- CREATE TABLE state (
--     id SERIAL PRIMARY KEY,
--     name TEXT NOT NULL,
--     abbreviation CHAR(2) UNIQUE NOT NULL
-- );

-- CREATE TABLE powerBall (
--     id SERIAL PRIMARY KEY,
--     state_id INTEGER NOT NULL REFERENCES state(id) ON DELETE CASCADE,
--     date TEXT,
--     nextDrawDate TEXT,
--     nextDrawJackpot BIGINT,
--     numbers INTEGER[],      -- array of numbers
--     extraFields TEXT[],     -- array of extra fields (strings)
--     gameName TEXT,
--     playName TEXT
-- );

-- CREATE TABLE mega_millions (
--     id SERIAL PRIMARY KEY,
--     state_id INTEGER NOT NULL REFERENCES state(id) ON DELETE CASCADE,
--     date TEXT,
--     nextDrawDate TEXT,
--     nextDrawJackpot BIGINT,
--     numbers INTEGER[],      -- array of numbers
--     extraFields TEXT[],     -- array of extra fields (strings)
--     gameName TEXT,
--     playName TEXT
-- );

-- CREATE TABLE cash4life (
--     id SERIAL PRIMARY KEY,
--     state_id INTEGER NOT NULL REFERENCES state(id) ON DELETE CASCADE,
--     date TEXT,
--     nextDrawDate TEXT,
--     nextDrawJackpot BIGINT,
--     numbers INTEGER[],      -- array of numbers
--     extraFields TEXT[],     -- array of extra fields (strings)
--     gameName TEXT,
--     playName TEXT
-- );

-- CREATE TABLE lotto (
--     id SERIAL PRIMARY KEY,
--     state_id INTEGER NOT NULL REFERENCES state(id) ON DELETE CASCADE,
--     date TEXT,
--     nextDrawDate TEXT,
--     nextDrawJackpot BIGINT,
--     numbers INTEGER[],      -- array of numbers
--     extraFields TEXT[],     -- array of extra fields (strings)
--     gameName TEXT,
--     playName TEXT
-- );

-- CREATE TABLE take_5 (
--     id SERIAL PRIMARY KEY,
--     state_id INTEGER NOT NULL REFERENCES state(id) ON DELETE CASCADE,
--     date TEXT,
--     nextDrawDate TEXT,
--     nextDrawJackpot BIGINT,
--     numbers INTEGER[],      -- array of numbers
--     extraFields TEXT[],     -- array of extra fields (strings)
--     gameName TEXT,
--     playName TEXT
-- );

-- CREATE TABLE pick_10 (
--     id SERIAL PRIMARY KEY,
--     state_id INTEGER NOT NULL REFERENCES state(id) ON DELETE CASCADE,
--     date TEXT,
--     nextDrawDate TEXT,
--     nextDrawJackpot BIGINT,
--     numbers INTEGER[],      -- array of numbers
--     extraFields TEXT[],     -- array of extra fields (strings)
--     gameName TEXT,
--     playName TEXT
-- );

-- CREATE TABLE win_4 (
--     id SERIAL PRIMARY KEY,
--     state_id INTEGER NOT NULL REFERENCES state(id) ON DELETE CASCADE,
--     date TEXT,
--     nextDrawDate TEXT,
--     nextDrawJackpot BIGINT,
--     numbers INTEGER[],      -- array of numbers
--     extraFields TEXT[],     -- array of extra fields (strings)
--     gameName TEXT,
--     playName TEXT
-- );

-- CREATE TABLE numbers (
--     id SERIAL PRIMARY KEY,
--     state_id INTEGER NOT NULL REFERENCES state(id) ON DELETE CASCADE,
--     date TEXT,
--     nextDrawDate TEXT,
--     nextDrawJackpot BIGINT,
--     numbers INTEGER[],      -- array of numbers
--     extraFields TEXT[],     -- array of extra fields (strings)
--     gameName TEXT,
--     playName TEXT
-- );

-- CREATE TABLE lucky_for_life (
--     id SERIAL PRIMARY KEY,
--     state_id INTEGER NOT NULL REFERENCES state(id) ON DELETE CASCADE,
--     date TEXT,
--     nextDrawDate TEXT,
--     nextDrawJackpot BIGINT,
--     numbers INTEGER[],      -- array of numbers
--     extraFields TEXT[],     -- array of extra fields (strings)
--     gameName TEXT,
--     playName TEXT
-- );

-- CREATE TABLE natural_state_jackpot (
--     id SERIAL PRIMARY KEY,
--     state_id INTEGER NOT NULL REFERENCES state(id) ON DELETE CASCADE,
--     date TEXT,
--     nextDrawDate TEXT,
--     nextDrawJackpot BIGINT,
--     numbers INTEGER[],      -- array of numbers
--     extraFields TEXT[],     -- array of extra fields (strings)
--     gameName TEXT,
--     playName TEXT
-- );

-- CREATE TABLE cash_4 (
--     id SERIAL PRIMARY KEY,
--     state_id INTEGER NOT NULL REFERENCES state(id) ON DELETE CASCADE,
--     date TEXT,
--     nextDrawDate TEXT,
--     nextDrawJackpot BIGINT,
--     numbers INTEGER[],      -- array of numbers
--     extraFields TEXT[],     -- array of extra fields (strings)
--     gameName TEXT,
--     playName TEXT
-- );

-- CREATE TABLE cash_3(
--     id SERIAL PRIMARY KEY,
--     state_id INTEGER NOT NULL REFERENCES state(id) ON DELETE CASCADE,
--     date TEXT,
--     nextDrawDate TEXT,
--     nextDrawJackpot BIGINT,
--     numbers INTEGER[],      -- array of numbers
--     extraFields TEXT[],     -- array of extra fields (strings)
--     gameName TEXT,
--     playName TEXT
-- );

-- CREATE TABLE the_pick (
--     id SERIAL PRIMARY KEY,
--     state_id INTEGER NOT NULL REFERENCES state(id) ON DELETE CASCADE,
--     date TEXT,
--     nextDrawDate TEXT,
--     nextDrawJackpot BIGINT,
--     numbers INTEGER[],      -- array of numbers
--     extraFields TEXT[],     -- array of extra fields (strings)
--     gameName TEXT,
--     playName TEXT
-- );

-- CREATE TABLE fantasy_5 (
--     id SERIAL PRIMARY KEY,
--     state_id INTEGER NOT NULL REFERENCES state(id) ON DELETE CASCADE,
--     date TEXT,
--     nextDrawDate TEXT,
--     nextDrawJackpot BIGINT,
--     numbers INTEGER[],      -- array of numbers
--     extraFields TEXT[],     -- array of extra fields (strings)
--     gameName TEXT,
--     playName TEXT
-- );

-- CREATE TABLE triple_twist (
--     id SERIAL PRIMARY KEY,
--     state_id INTEGER NOT NULL REFERENCES state(id) ON DELETE CASCADE,
--     date TEXT,
--     nextDrawDate TEXT,
--     nextDrawJackpot BIGINT,
--     numbers INTEGER[],      -- array of numbers
--     extraFields TEXT[],     -- array of extra fields (strings)
--     gameName TEXT,
--     playName TEXT
-- );

-- CREATE TABLE pick_3 (
--     id SERIAL PRIMARY KEY,
--     state_id INTEGER NOT NULL REFERENCES state(id) ON DELETE CASCADE,
--     date TEXT,
--     nextDrawDate TEXT,
--     nextDrawJackpot BIGINT,
--     numbers INTEGER[],      -- array of numbers
--     extraFields TEXT[],     -- array of extra fields (strings)
--     gameName TEXT,
--     playName TEXT
-- );

-- CREATE TABLE daily_derby(
--     id SERIAL PRIMARY KEY,
--     state_id INTEGER NOT NULL REFERENCES state(id) ON DELETE CASCADE,
--     date TEXT,
--     nextDrawDate TEXT,
--     nextDrawJackpot BIGINT,
--     numbers INTEGER[],      -- array of numbers
--     extraFields TEXT[],     -- array of extra fields (strings)
--     gameName TEXT,
--     playName TEXT
-- );

-- CREATE TABLE superlotto_plus(
--     id SERIAL PRIMARY KEY,
--     state_id INTEGER NOT NULL REFERENCES state(id) ON DELETE CASCADE,
--     date TEXT,
--     nextDrawDate TEXT,
--     nextDrawJackpot BIGINT,
--     numbers INTEGER[],      -- array of numbers
--     extraFields TEXT[],     -- array of extra fields (strings)
--     gameName TEXT,
--     playName TEXT
-- );



















-- CREATE TABLE powerBall (
--     id SERIAL PRIMARY KEY,
--     date text,
--     one INTEGER,
--     two INTEGER,
--     three INTEGER,
--     four INTEGER,
--     five INTEGER,
--     powerBall_Lucky INTEGER,
--     powerPlay INTEGER,
--     amount INTEGER,
--     image text
-- );
-- CREATE TABLE mega_millions (
--     id SERIAL PRIMARY KEY,
--     date text,
--     one INTEGER,
--     two INTEGER,
--     three INTEGER,
--     four INTEGER,
--     five INTEGER,
--     mega_millions_lucky INTEGER,
--     megaplier INTEGER,
--     amount INTEGER,
--     image text
-- );
-- CREATE TABLE new_York_Lotto (
--     id SERIAL PRIMARY KEY,
--     date text,
--     one INTEGER,
--     two INTEGER,
--     three INTEGER,
--     four INTEGER,
--     five INTEGER,
--     six INTEGER,
--     bonus INTEGER,
--     amount INTEGER,
--     image text
-- );
-- CREATE TABLE pick_10 (
--     id SERIAL PRIMARY KEY,
--     date text,
--     one INTEGER,
--     two INTEGER,
--     three INTEGER,
--     four INTEGER,
--     five INTEGER,
--     six INTEGER,
--     seven INTEGER,
--     eight INTEGER,
--     nine INTEGER,
--     ten INTEGER,
--     eleven INTEGER,
--     twelve INTEGER,
--     thirteen INTEGER,
--     fourteen INTEGER,
--     fifteen INTEGER,
--     sixteen INTEGER,
--     seventeen INTEGER,
--     eighteen INTEGER,
--     nineteen INTEGER,
--     twenty INTEGER,
--     amount INTEGER,
--     image text
-- );
-- CREATE TABLE cash4Life (
--     id SERIAL PRIMARY KEY,
--     date text,
--     one INTEGER,
--     two INTEGER,
--     three INTEGER,
--     four INTEGER,
--     five INTEGER,
--     cashBall INTEGER,
--     amount INTEGER,
--     image text
-- );
-- CREATE TABLE take_5_Day (
--     id SERIAL PRIMARY KEY,
--     date text,
--     one INTEGER,
--     two INTEGER,
--     three INTEGER,
--     four INTEGER,
--     five INTEGER,
--     amount INTEGER,
--     image text,
--     timedate text
-- );
-- CREATE TABLE take_5_Night (
--     id SERIAL PRIMARY KEY,
--     date text,
--     one INTEGER,
--     two INTEGER,
--     three INTEGER,
--     four INTEGER,
--     five INTEGER,
--     amount INTEGER,
--     image text
-- );
-- CREATE TABLE win_4_Day (
--     id SERIAL PRIMARY KEY,
--     date text,
--     one INTEGER,
--     two INTEGER,
--     three INTEGER,
--     four INTEGER,
--     amount INTEGER,
--     image text,
--     timedate text
-- );
-- CREATE TABLE win_4_Night (
--     id SERIAL PRIMARY KEY,
--     date text,
--     one INTEGER,
--     two INTEGER,
--     three INTEGER,
--     four INTEGER,
--     amount INTEGER,
--     image text
-- );
-- CREATE TABLE numbers_Day (
--     id SERIAL PRIMARY KEY,
--     date text,
--     one INTEGER,
--     two INTEGER,
--     three INTEGER,
--     amount INTEGER,
--     image text,
--     timedate text
-- );
-- CREATE TABLE numbers_Night (
--     id SERIAL PRIMARY KEY,
--     date text,
--     one INTEGER,
--     two INTEGER,
--     three INTEGER,
--     amount INTEGER,
--     image text
-- );
-- CREATE TABLE admission (
--     id SERIAL PRIMARY KEY,
--     date text,
--     username text,
--     email text ,
--     password text ,
--     image text
-- );
-- CREATE TABLE generate_Numbers_powerBall(
--     id SERIAL PRIMARY KEY,
--     date text,
--     storage text[],
--     amount INTEGER
-- );

-- CREATE TABLE generate_Numbers_mega_Millions(
--      id SERIAL PRIMARY KEY,
--     date text,
--     storage text[],
--     amount INTEGER
-- );
-- CREATE TABLE generate_Numbers_new_York_Lotto(
--     id SERIAL PRIMARY KEY,
--     date text,
--     storage text[],
--     amount INTEGER
-- );

-- CREATE TABLE generate_Numbers_pick_10(
--     id SERIAL PRIMARY KEY,
--     date text,
--     storage text[],
--     amount INTEGER
-- );
-- CREATE TABLE generate_Numbers_cash4Life(
--     id SERIAL PRIMARY KEY,
--     date text,
--     storage text[],
--     amount INTEGER
-- );
-- CREATE TABLE generate_Numbers_take_5_day(
--     id SERIAL PRIMARY KEY,
--     date text,
--     storage text[],
--     amount INTEGER
-- );
-- CREATE TABLE generate_Numbers_take_5_Night(
--     id SERIAL PRIMARY KEY,
--     date text,
--     storage text[],
--     amount INTEGER
-- );
-- CREATE TABLE generate_Numbers_win_4_Day(
--     id SERIAL PRIMARY KEY,
--     date text,
--     storage text[],
--     amount INTEGER
-- );
-- CREATE TABLE generate_Numbers_win_4_Night(
--     id SERIAL PRIMARY KEY,
--     date text,
--     storage text[],
--     amount INTEGER
-- );
-- CREATE TABLE generate_Numbers_numbers_Day(
--     id SERIAL PRIMARY KEY,
--     date text,
--     storage text[],
--     amount INTEGER
-- );
-- CREATE TABLE generate_Numbers_numbers_Night(
--     id SERIAL PRIMARY KEY,
--     date text,
--     storage text[],
--     amount INTEGER
-- );
-- CREATE TABLE recollections_of_winnings (
--     id SERIAL PRIMARY KEY,
--     date text,
--     storage text[],
--     amount INTEGER
-- );
